# version: "3.7"
# services:                         
#   xtlab-mssql:
#     user: root
#     image: "mcr.microsoft.com/mssql/server:2019-latest"
#     container_name: KizspyApp
#     restart: always
#     hostname: mssql
#     environment: 
#       SA_PASSWORD: 12345 #Thiết lập password
#       ACCEPT_EULA: 'Y'
#       # Express: 

#     volumes:
#       - mssqlvolume:/var/opt/mssql/data # thư mục lưu DB
#       # - ./bk:/var/opt/mssql/backup
#     ports:
#       - "1433:1433"     
                        
# volumes:                                
#     mssqlvolume:        
#       name: KizspyApp
version: 'version: "3.7"'
services:
  kizspy-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: kizspy-sql
    restart: always
    environment:
      SA_PASSWORD: "FUHCM@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/var/opt/mssql/backup
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
